const api='/api/v1';
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
let state={customers:[],products:[],categories:[],orders:[],artwork:[],dashboard:null,currentCustomer:null,folder:null,files:[]};
let selectedCustomerFileIds=new Set();let currentCustomerFileId=null;
let stagedOrderDesigns=[];
const orderStatuses=['Draft','Awaiting Artwork','Designing','Awaiting Approval','Approved','Gang Sheet Preparation','Ready for Production','Printing','Powder and Cure','Quality Check','Cutting','Packing','Ready for Dispatch','Dispatched','Completed','Cancelled'];
const csrf=()=>decodeURIComponent((document.cookie.match(/(?:^|; )kms_erp_csrf=([^;]*)/)||[])[1]||'');
async function request(path,options={}){const method=options.method||'GET';const headers={...(options.headers||{})};if(!(options.body instanceof FormData))headers['Content-Type']='application/json';if(!['GET','HEAD'].includes(method))headers['X-CSRF-Token']=csrf();const response=await fetch(api+path,{credentials:'include',...options,headers});if(response.status===401){showLogin();throw new Error('Please sign in again.')}const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.detail||'Request failed');return data}
function money(v){return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(Number(v||0))}
function escapeHtml(v){const d=document.createElement('div');d.textContent=v??'';return d.innerHTML}
function notify(message){const modal=document.querySelector('dialog[open]');if(modal){let local=modal.querySelector('.dialog-notice');if(!local){local=document.createElement('div');local.className='dialog-notice';modal.firstElementChild?.prepend(local)}local.textContent=message;local.classList.add('visible');setTimeout(()=>local.classList.remove('visible'),4000);return}const n=$('#notice');n.textContent=message;n.classList.remove('hidden');setTimeout(()=>n.classList.add('hidden'),3000)}
function showLogin(){$('#login-view').classList.remove('hidden');$('#app-view').classList.add('hidden')}
function configureStaffMessages(){const frame=$('#staff-messages-frame');if(!frame||frame.getAttribute('src'))return;frame.src=`${window.location.protocol}//${window.location.hostname}:3011/admin/messages`}
function showApp(user){$('#login-view').classList.add('hidden');$('#app-view').classList.remove('hidden');$('#account-name').textContent=user.full_name;$('#account-org').textContent=user.organization_name;$('#developer-badge').classList.toggle('hidden',user.username!=='developer');configureStaffMessages();loadAll()}
async function loadAll(){try{const status=$('#customer-status').value;const customerQuery=status==='all'?'active=':`active=${status}`;[state.customers,state.products,state.categories,state.orders,state.artwork,state.dashboard]=await Promise.all([request('/customers?'+customerQuery),request('/products'),request('/categories'),request('/orders'),request('/artwork'),request('/dashboard?period='+$('#dashboard-period').value)]);renderAll()}catch(e){notify(e.message)}}
function table(headers,rows){if(!rows.length)return '<div class="empty">No records yet.</div>';return `<table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table>`}
function renderAll(){renderDashboard();renderCustomers();renderProducts();renderOrders();renderArtwork();fillSelects()}
function renderDashboard(){if(!state.dashboard)return;const m=state.dashboard.metrics;$('#metric-orders').textContent=m.todays_orders;$('#metric-pending').textContent=m.pending_orders;$('#metric-production').textContent=m.in_production;$('#metric-completed').textContent=m.completed_jobs;$('#metric-payments').textContent=m.pending_payments;$('#metric-revenue').textContent=`INR ${Number(m.revenue).toLocaleString('en-IN',{minimumFractionDigits:2})}`;$('#pipeline').innerHTML=state.dashboard.pipeline.map(s=>`<article><span>${escapeHtml(s.name)}</span><strong>${s.count}</strong></article>`).join('');$('#recent-activity').innerHTML=state.dashboard.recent_activity.length?state.dashboard.recent_activity.map(a=>`<article><strong>${escapeHtml(a.action.replaceAll('.',' '))}</strong><small>${escapeHtml(a.details)}</small></article>`).join(''):'<div class="empty">No activity in this period</div>';$('#low-stock').innerHTML=state.dashboard.low_stock.length?state.dashboard.low_stock.map(i=>`<article><strong>${escapeHtml(i.name)}</strong><small>${i.available} ${escapeHtml(i.unit)}</small></article>`).join(''):'<div class="empty">No low-stock items</div>'}
function renderCustomers(){const q=$('#customer-search').value.toLowerCase();const list=state.customers.filter(c=>`${c.code} ${c.name} ${c.business_name} ${c.phone}`.toLowerCase().includes(q));$('#customer-list').innerHTML=table(['Code','Customer','Phone / WhatsApp','Delivery','Rate','Status','Actions'],list.map(c=>`<tr><td><strong>${escapeHtml(c.code)}</strong></td><td>${escapeHtml(c.business_name||c.name)}<br><small>${escapeHtml(c.name)}</small></td><td>${escapeHtml(c.phone)}<br><small>${escapeHtml(c.whatsapp_number||'')}</small></td><td>${escapeHtml(c.delivery_type)}<br><small>${escapeHtml(c.preferred_courier||c.other_transport_name||'')}</small></td><td>${money(c.preferred_rate)}</td><td><span class="badge">${c.is_active?'Active':'Inactive'}</span></td><td class="row-actions"><button data-customer-action="view" data-id="${c.id}">View</button><button data-customer-action="folder" data-id="${c.id}">Open folder</button><button data-customer-action="edit" data-id="${c.id}">Edit</button>${c.is_active?`<button data-customer-action="deactivate" data-id="${c.id}">Deactivate</button>`:''}<button class="danger" data-customer-action="delete" data-id="${c.id}">Delete</button></td></tr>`))}
function setFormValue(form,name,value){const field=form.elements[name];if(field)field.value=value??''}
function customerPayload(form){const v=Object.fromEntries(new FormData(form));const addr=prefix=>({line1:v[prefix+'_line1'],line2:v[prefix+'_line2'],city:v[prefix+'_city'],landmark:v[prefix+'_landmark'],district:v[prefix+'_district'],state:v[prefix+'_state'],postal_code:v[prefix+'_postal_code'],country:v[prefix+'_country']||'India'});return {code:v.code,name:v.name,phone:v.phone,business_name:v.business_name,whatsapp_number:v.whatsapp_number,delivery_type:v.delivery_type,preferred_courier:v.preferred_courier,other_transport_name:v.other_transport_name,preferred_rate:v.preferred_rate||'0',email:v.email||null,gst_number:v.gst_number,billing_address:addr('billing'),shipping_address:addr('shipping'),notes:v.notes}}
function fillCustomerForm(c=null){const f=$('#customer-form');f.reset();f.dataset.relationshipConfirmed='false';setFormValue(f,'billing_country','India');setFormValue(f,'shipping_country','India');setFormValue(f,'preferred_rate','0.00');setFormValue(f,'id',c?.summary.id||'');$('#customer-form-title').textContent=c?'Edit customer':'New customer';if(c){const s=c.summary;for(const name of ['code','name','business_name','phone','whatsapp_number','delivery_type','preferred_courier','other_transport_name','preferred_rate','email'])setFormValue(f,name,s[name]);setFormValue(f,'gst_number',c.gst_number);setFormValue(f,'notes',c.notes);for(const p of ['billing','shipping'])for(const key of ['line1','line2','city','landmark','district','state','postal_code','country'])setFormValue(f,`${p}_${key}`,c[`${p}_address`][key])}updateDeliveryFields();$('#customer-dialog').showModal()}
function updateDeliveryFields(){const f=$('#customer-form');const local=f.elements.delivery_type.value==='Local';const other=!local&&f.elements.preferred_courier.value==='OTHER TRANSPORT';$('[data-courier]').classList.toggle('hidden',local);$('[data-other-transport]').classList.toggle('hidden',!other);f.elements.preferred_courier.required=!local;f.elements.other_transport_name.required=other}
async function getCustomer(id){state.currentCustomer=await request('/customers/'+id);return state.currentCustomer}
function addressHtml(title,a){return `<section class="detail-block"><h3>${title}</h3><p>${escapeHtml(a.line1)} ${escapeHtml(a.line2)}</p><p>${escapeHtml(a.city)} ${escapeHtml(a.landmark)} ${escapeHtml(a.district)}</p><p>${escapeHtml(a.state)} ${escapeHtml(a.postal_code)} ${escapeHtml(a.country)}</p></section>`}
async function showCustomer(id){const c=await getCustomer(id);const s=c.summary;$('#customer-details-title').textContent=s.display_identifier;$('#customer-details-content').innerHTML=`<div class="detail-grid"><section class="detail-block"><h3>Customer details</h3><p><b>Name:</b> ${escapeHtml(s.name)}</p><p><b>Business:</b> ${escapeHtml(s.business_name)}</p><p><b>Phone:</b> ${escapeHtml(s.phone)}</p><p><b>WhatsApp:</b> ${escapeHtml(c.whatsapp_number)}</p><p><b>Email:</b> ${escapeHtml(s.email||'')}</p><p><b>GST:</b> ${escapeHtml(c.gst_number)}</p><p><b>Delivery:</b> ${escapeHtml(s.delivery_type)} ${escapeHtml(s.preferred_courier||s.other_transport_name)}</p><p><b>Preferred rate:</b> ${money(s.preferred_rate)}</p></section>${addressHtml('Billing address',c.billing_address)}${addressHtml('Shipping address',c.shipping_address)}<section class="detail-block"><h3>Notes</h3><p>${escapeHtml(c.notes||'No notes')}</p></section></div>`;$('#customer-details-dialog').showModal()}
async function openCustomerFolder(id){const c=await getCustomer(id);state.folder=await request(`/customers/${id}/folders`);state.selectedDate=state.folder.dates[0]||'';state.selectedFolder='Design';selectedCustomerFileIds.clear();currentCustomerFileId=null;$('#folder-title').textContent=`Customer folder — ${c.summary.display_identifier}`;$('#folder-prefix').textContent=state.folder.storage_prefix;$('#folder-location').textContent=c.summary.display_identifier;renderFolderDates();$('#customer-folder-dialog').showModal();await loadCustomerFiles()}
function renderFolderDates(){$('#customer-folder-tree').innerHTML=state.folder.dates.length?state.folder.dates.map(d=>`<div class="date-node"><button data-folder-date="${d}">▾ ${d}</button>${['Design','Gangsheet','Invoice Copy','Payment Receipt'].map(f=>`<button class="folder-node ${state.selectedDate===d&&state.selectedFolder===f?'active':''}" data-date="${d}" data-folder="${f}">${escapeHtml(f)}</button>`).join('')}</div>`).join(''):'<div class="empty">No date folders yet.<br>Create today’s folder when work begins.</div>'}
async function loadCustomerFiles(){if(!state.selectedDate){state.files=[];return renderCustomerFiles()}state.files=await request(`/customers/${state.currentCustomer.summary.id}/files?date_name=${encodeURIComponent(state.selectedDate)}&folder_name=${encodeURIComponent(state.selectedFolder)}`);selectedCustomerFileIds.clear();currentCustomerFileId=null;renderCustomerFiles();showCustomerFilePreview(null)}
function formatFileSize(bytes){if(bytes<1024)return `${bytes} B`;if(bytes<1048576)return `${(bytes/1024).toFixed(1)} KB`;return `${(bytes/1048576).toFixed(1)} MB`}
function renderCustomerFiles(){$('#customer-file-list').innerHTML=state.files.length?state.files.map(f=>`<tr class="${currentCustomerFileId===f.id?'selected':''}" data-preview-file="${f.id}"><td><input type="checkbox" data-select-file="${f.id}" ${selectedCustomerFileIds.has(f.id)?'checked':''}></td><td>${escapeHtml(f.original_name)}</td><td>${formatFileSize(f.size_bytes)}</td><td>${escapeHtml(f.transfer_state[0].toUpperCase()+f.transfer_state.slice(1))}</td><td>${new Date(f.created_at).toLocaleString()}</td></tr>`).join(''):'<tr><td colspan="5" class="empty">No files in this folder.</td></tr>';const upload=$('#customer-file-upload');upload.disabled=state.selectedFolder!=='Design';upload.closest('label').classList.toggle('disabled',upload.disabled);updateCustomerFileActions()}
function showCustomerFilePreview(file){currentCustomerFileId=file?.id||null;$('#customer-preview-name').textContent=file?.original_name||'No file selected';const preview=$('#customer-file-preview');if(!file){preview.innerHTML='<span>Select an image or PDF to preview</span>';updateCustomerFileActions();return}const url=`${api}/customer-files/${file.id}`;if(file.content_type==='application/pdf'||file.original_name.toLowerCase().endsWith('.pdf'))preview.innerHTML=`<iframe src="${url}" title="${escapeHtml(file.original_name)}"></iframe>`;else if(file.content_type.startsWith('image/'))preview.innerHTML=`<img src="${url}" alt="${escapeHtml(file.original_name)}">`;else preview.innerHTML='<span>Preview is not available for this file type.<br>Use Open or Download.</span>';renderCustomerFiles();updateCustomerFileActions()}
function selectedCustomerFiles(){const ids=selectedCustomerFileIds.size?[...selectedCustomerFileIds]:(currentCustomerFileId?[currentCustomerFileId]:[]);return ids.map(id=>state.files.find(f=>f.id===id)).filter(Boolean)}
function updateCustomerFileActions(){const count=selectedCustomerFiles().length;for(const action of ['edit-selected-file','open-selected-file']){const button=document.querySelector(`[data-action="${action}"]`);if(button)button.disabled=count!==1}for(const action of ['copy-selected-files','delete-selected-files','download-selected-files']){const button=document.querySelector(`[data-action="${action}"]`);if(button)button.disabled=count<1}}
async function openCopyFilesDialog(){const files=selectedCustomerFiles();if(!files.length)return notify('Select one or more files first.');const form=$('#copy-files-form');form.elements.customer_id.innerHTML=state.customers.filter(c=>c.is_active).map(c=>`<option value="${c.id}">${escapeHtml(c.display_identifier)}</option>`).join('');form.dataset.fileIds=files.map(f=>f.id).join(',');await loadCopyDates();$('#copy-files-dialog').showModal()}
async function loadCopyDates(){const form=$('#copy-files-form');const id=form.elements.customer_id.value;const folders=id?await request(`/customers/${id}/folders`):{dates:[]};form.elements.date_name.innerHTML=folders.dates.map(d=>`<option>${d}</option>`).join('');$('#copy-files-message').textContent=folders.dates.length?'':'The selected customer has no date folder. Create one first.';form.querySelector('.primary').disabled=!folders.dates.length}
function renderProducts(){const q=$('#product-search').value.toLowerCase();const list=state.products.filter(p=>`${p.code} ${p.name} ${p.category}`.toLowerCase().includes(q));$('#product-list').innerHTML=table(['Code','Product','Category','Unit','Base price','Tax'],list.map(p=>`<tr><td><strong>${escapeHtml(p.code)}</strong></td><td>${escapeHtml(p.name)}</td><td>${escapeHtml(p.category)}</td><td>${escapeHtml(p.unit)}</td><td>${money(p.base_price)}</td><td>${escapeHtml(p.tax_rate)}%</td></tr>`))}
function quickStatusOptions(order){if(order.status==='Cancelled')return '<option value="Cancelled">Canceled</option>';if(order.status==='Completed')return '<option>Completed</option>';const quick=['Designing','Printing','Completed'];const start=quick.includes(order.status)?quick.indexOf(order.status)+1:0;return `<option value="">${quick.includes(order.status)?escapeHtml(order.status):'Select status'}</option>${quick.slice(start).map(s=>`<option>${s}</option>`).join('')}<option value="Cancelled">Canceled</option>`}
function renderOrders(){const q=$('#order-search').value.toLowerCase();const list=state.orders.filter(o=>`${o.order_number} ${o.customer_name} ${o.customer_code}`.toLowerCase().includes(q));$('#order-list').innerHTML=table(['Order','Customer','Product type','Open design','Status'],list.map(o=>`<tr data-order-row="${o.id}"><td><strong>${escapeHtml(o.order_number)}</strong></td><td>${escapeHtml(o.customer_display_identifier)}</td><td>${escapeHtml(o.order_type)}</td><td><button data-order-action="designs" data-id="${o.id}">Open design</button></td><td><select data-order-status="${o.id}" ${['Cancelled','Completed'].includes(o.status)?'disabled':''}>${quickStatusOptions(o)}</select></td></tr>`))}
function renderArtwork(){const q=$('#artwork-search').value.toLowerCase();const list=state.artwork.filter(a=>`${a.title} ${a.customer_name} ${a.order_number} ${a.tags.join(' ')}`.toLowerCase().includes(q));$('#artwork-list').innerHTML=table(['Preview','Design','Customer / order','Version','Approval','File'],list.map(a=>{const v=a.latest_version;return `<tr><td><img class="design-preview" src="${api}/artwork/versions/${v.id}/preview" alt="" onerror="this.replaceWith(document.createTextNode('CDR'))"></td><td><strong>${escapeHtml(a.title)}</strong><br><small>${escapeHtml(a.tags.join(', '))}</small></td><td>${escapeHtml(a.customer_name||'Unassigned')}<br><small>${escapeHtml(a.order_number||'')}</small></td><td>v${v.version_number} · ${a.version_count} total</td><td><span class="badge">${escapeHtml(v.approval_status)}</span></td><td><a class="file-link" href="${api}/artwork/versions/${v.id}/original">Open / download</a></td></tr>`}))}
function fillSelects(){$('#product-form [name=category_id]').innerHTML=state.categories.map(c=>`<option value="${c.id}">${escapeHtml(c.name)}</option>`).join('');const orderCustomer=$('#order-form [name=customer_id]');const selected=orderCustomer.value;orderCustomer.innerHTML='<option value="">Select customer</option>'+state.customers.filter(c=>c.is_active).map(c=>`<option value="${c.id}">${escapeHtml(c.display_identifier)}</option>`).join('');orderCustomer.value=selected;$('#artwork-form [name=customer_id]').innerHTML='<option value="">None</option>'+state.customers.map(c=>`<option value="${c.id}">${escapeHtml(c.display_identifier)}</option>`).join('');$('#artwork-form [name=order_id]').innerHTML='<option value="">None</option>'+state.orders.map(o=>`<option value="${o.id}">${escapeHtml(o.order_number+' - '+o.customer_name)}</option>`).join('')}
function openNewOrder(){stagedOrderDesigns.forEach(x=>URL.revokeObjectURL(x.url));stagedOrderDesigns=[];$('#order-form').reset();fillSelects();renderOrderDesigns();$('#order-design-status').textContent='Select a customer before importing designs';$('#order-dialog').showModal()}
function renderOrderDesigns(){$('#order-design-previews').innerHTML=stagedOrderDesigns.length?stagedOrderDesigns.map((x,i)=>`<article data-order-preview="${i}"><button type="button" data-remove-order-design="${i}">&times;</button><div>${x.file.type.startsWith('image/')?`<img src="${x.url}" alt="">`:escapeHtml(x.file.name.split('.').pop().toUpperCase())}</div><small title="${escapeHtml(x.file.name)}">${escapeHtml(x.displayName||x.file.name)}</small></article>`).join(''):'<div class="empty">No designs selected</div>';$('#order-design-status').textContent=stagedOrderDesigns.length?`${stagedOrderDesigns.length} design(s) ready — files upload when you click Save`:($('#order-form [name=customer_id]').value?'No designs selected':'Select a customer before importing designs')}
async function uploadOrderDesigns(customerId){if(!stagedOrderDesigns.length)return [];const localDate=new Date();const today=`${localDate.getFullYear()}-${String(localDate.getMonth()+1).padStart(2,'0')}-${String(localDate.getDate()).padStart(2,'0')}`;let folders=await request(`/customers/${customerId}/folders`);if(!folders.dates.includes(today))folders=await request(`/customers/${customerId}/folders`,{method:'POST',body:JSON.stringify({folder_date:today})});const ids=[];for(const item of stagedOrderDesigns){const body=new FormData();body.append('file',item.file);body.append('date_name',today);body.append('folder_name','Design');const record=await request(`/customers/${customerId}/files`,{method:'POST',body});ids.push(record.id)}return ids}
async function showOrder(id){state.currentOrder=await request('/orders/'+id);const d=state.currentOrder,s=d.summary;$('#order-details-title').textContent=`${s.order_number} · ${s.customer_name}`;$('#order-details-content').innerHTML=`<div class="detail-grid"><section class="detail-block"><p><b>Customer No.:</b> ${escapeHtml(s.customer_code)}</p><p><b>Customer:</b> ${escapeHtml(s.customer_name)}</p><p><b>Product type:</b> ${escapeHtml(s.order_type)}</p><p><b>Status:</b> ${escapeHtml(s.status)}</p><p><b>Priority:</b> ${escapeHtml(s.priority)}</p><p><b>Due date:</b> ${escapeHtml(s.due_date||'Not set')}</p><p><b>Notes:</b> ${escapeHtml(d.notes||'—')}</p></section><section class="detail-block"><p><b>Subtotal:</b> ${money(d.subtotal)}</p><p><b>Discount:</b> ${money(d.discount)}</p><p><b>Tax:</b> ${money(d.tax)}</p><p><b>Advance:</b> ${money(d.advance)}</p><p><b>Total:</b> ${money(s.total)}</p><p><b>Balance:</b> ${money(s.balance)}</p></section></div>`;$('#order-status-timeline').innerHTML=d.status_history.map(h=>`<article><strong>${new Date(h.changed_at).toLocaleString()} · ${escapeHtml(h.from_status?h.from_status+' → '+h.to_status:h.to_status)}</strong><small>${escapeHtml(h.note||'')}</small></article>`).join('');$('#order-detail-status').innerHTML=orderStatuses.map(x=>`<option ${x===s.status?'selected':''}>${x}</option>`).join('');$('#order-status-note').value='';$('#order-details-dialog').showModal()}
async function showOrderDesigns(details){const records=[];for(const id of details.design_file_ids){try{records.push({id,name:`Design ${id}`,url:`${api}/customer-files/${id}`})}catch{}}$('#design-preview-title').textContent=`${details.summary.order_number} — Designs`;$('#design-preview-content').innerHTML=records.length?`<div class="order-open-designs">${records.map(r=>`<article><img src="${r.url}" alt="" onerror="this.replaceWith(document.createTextNode('FILE'))"><a href="${r.url}" target="_blank">Open design ${r.id}</a></article>`).join('')}</div>`:'<div class="empty">This order has no saved designs.</div>';$('#design-preview-dialog').showModal()}
function openDialog(id){fillSelects();$(id).showModal()}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();$('#login-error').textContent='';const body=Object.fromEntries(new FormData(e.target));try{showApp(await request('/auth/login',{method:'POST',body:JSON.stringify(body)}))}catch(err){$('#login-error').textContent=err.message}});
$('#logout').addEventListener('click',async()=>{try{await request('/auth/logout',{method:'POST'});}finally{showLogin()}});
$('#navigation').addEventListener('click',e=>{if(!e.target.dataset.view)return;$$('#navigation button').forEach(b=>b.classList.toggle('active',b===e.target));$$('.page').forEach(p=>p.classList.toggle('hidden',p.id!==e.target.dataset.view));$('#page-title').textContent=e.target.textContent;$('.sidebar').classList.remove('open')});
$('#menu-button').onclick=()=>$('.sidebar').classList.toggle('open');
document.addEventListener('click',e=>{const action=e.target.dataset.action;if(action==='new-customer')fillCustomerForm();if(action==='new-category')openDialog('#category-dialog');if(action==='new-product')openDialog('#product-dialog');if(action==='new-artwork')openDialog('#artwork-dialog');if(action==='refresh-dashboard')loadAll();if(e.target.dataset.viewLink)document.querySelector(`#navigation [data-view="${e.target.dataset.viewLink}"]`).click();if(action==='new-order'){if(!state.customers.length)return notify('Add a customer first.');openNewOrder()}if(e.target.hasAttribute('data-close'))e.target.closest('dialog').close()});
$('#customer-search').oninput=renderCustomers;$('#customer-status').onchange=loadAll;$('#product-search').oninput=renderProducts;$('#order-search').oninput=renderOrders;$('#artwork-search').oninput=renderArtwork;$('#dashboard-period').onchange=loadAll;
$('#customer-form [name=delivery_type]').onchange=updateDeliveryFields;$('#customer-form [name=preferred_courier]').onchange=updateDeliveryFields;
for(const prefix of ['billing','shipping'])$(`#customer-form [name=${prefix}_postal_code]`).onblur=async e=>{if(!/^\d{6}$/.test(e.target.value))return;try{const found=await request('/pincodes/'+e.target.value);setFormValue($('#customer-form'),prefix+'_district',found.district);setFormValue($('#customer-form'),prefix+'_state',found.state)}catch{}}
$('#customer-form').onsubmit=async e=>{e.preventDefault();const form=e.target;if(form.dataset.relationshipConfirmed!=='true'){form.dataset.relationshipConfirmed='true';if(confirm('Are the WhatsApp number and shipping address the same as the phone number and billing address above?')){setFormValue(form,'whatsapp_number',form.elements.phone.value);for(const key of ['line1','line2','city','landmark','district','state','postal_code','country'])setFormValue(form,'shipping_'+key,form.elements['billing_'+key].value)}else{form.elements.whatsapp_number.focus();return}}const id=form.elements.id.value;try{const saved=await request(id?`/customers/${id}`:'/customers',{method:id?'PUT':'POST',body:JSON.stringify(customerPayload(form))});form.closest('dialog').close();form.reset();notify(id?'Customer updated':'Customer created');await loadAll();if(state.orderAddingCustomer){state.orderAddingCustomer=false;fillSelects();$('#order-form [name=customer_id]').value=saved.summary.id;$('#order-dialog').showModal();renderOrderDesigns()}}catch(err){notify(err.message)}};
$('#category-form').onsubmit=async e=>{e.preventDefault();try{await request('/categories',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target))) });e.target.closest('dialog').close();e.target.reset();notify('Category created');await loadAll()}catch(err){notify(err.message)}};
$('#product-form').onsubmit=async e=>{e.preventDefault();const b=Object.fromEntries(new FormData(e.target));b.category_id=Number(b.category_id);try{await request('/products',{method:'POST',body:JSON.stringify(b)});e.target.closest('dialog').close();e.target.reset();notify('Product created');await loadAll()}catch(err){notify(err.message)}};
$('#order-form').onsubmit=async e=>{e.preventDefault();const customerId=Number(e.target.elements.customer_id.value);if(!customerId)return notify('Select a customer first.');try{$('#order-design-status').textContent='Uploading designs…';const designIds=await uploadOrderDesigns(customerId);const details=await request('/orders',{method:'POST',body:JSON.stringify({customer_id:customerId,order_type:e.target.elements.order_type.value,items:[],design_file_ids:designIds})});for(const item of stagedOrderDesigns){const body=new FormData();body.append('file',item.file);body.append('title',item.file.name.replace(/\.[^.]+$/,''));body.append('customer_id',String(customerId));body.append('order_id',String(details.summary.id));body.append('notes','Imported during order creation');try{await request('/artwork',{method:'POST',body})}catch{}}e.target.closest('dialog').close();stagedOrderDesigns.forEach(x=>URL.revokeObjectURL(x.url));stagedOrderDesigns=[];notify('Order created');await loadAll();await showOrder(details.summary.id)}catch(err){notify(err.message);$('#order-design-status').textContent=err.message}};
$('#order-form').onclick=e=>{if(e.target.dataset.action==='order-add-customer'){state.orderAddingCustomer=true;$('#order-dialog').close();fillCustomerForm()}};
$('#order-form [name=customer_id]').onchange=renderOrderDesigns;
$('#order-design-input').onchange=async e=>{const customerId=$('#order-form [name=customer_id]').value;if(!customerId){e.target.value='';return notify('Select a customer before importing.')}const existing=new Set(stagedOrderDesigns.map(x=>`${x.file.name}:${x.file.size}:${x.file.lastModified}`));const additions=[...e.target.files].filter(file=>!existing.has(`${file.name}:${file.size}:${file.lastModified}`));try{const names=additions.length?await request(`/customers/${customerId}/design-filenames`,{method:'POST',body:JSON.stringify({source_names:additions.map(f=>f.name)})}):[];additions.forEach((file,i)=>stagedOrderDesigns.push({file,url:URL.createObjectURL(file),displayName:names[i]||file.name}));e.target.value='';renderOrderDesigns()}catch(err){notify(err.message)}};
$('#order-design-previews').onclick=e=>{const remove=e.target.closest('[data-remove-order-design]');if(remove){const [item]=stagedOrderDesigns.splice(Number(remove.dataset.removeOrderDesign),1);URL.revokeObjectURL(item.url);renderOrderDesigns();return}const tile=e.target.closest('[data-order-preview]');if(tile){const item=stagedOrderDesigns[Number(tile.dataset.orderPreview)];$('#design-preview-title').textContent=`Design preview — ${item.file.name}`;$('#design-preview-content').innerHTML=item.file.type.startsWith('image/')?`<img src="${item.url}" alt="">`:`<iframe src="${item.url}" title=""></iframe>`;$('#design-preview-dialog').showModal()}};
$('#order-list').onclick=async e=>{const button=e.target.closest('[data-order-action]');const row=e.target.closest('[data-order-row]');try{if(button?.dataset.orderAction==='designs'){const details=await request('/orders/'+button.dataset.id);await showOrderDesigns(details);return}if(row&&!e.target.closest('button,select'))await showOrder(Number(row.dataset.orderRow))}catch(err){notify(err.message)}};
$('#order-list').ondblclick=async e=>{const row=e.target.closest('[data-order-row]');if(row)try{await showOrder(Number(row.dataset.orderRow))}catch(err){notify(err.message)}};
$('#order-list').onchange=async e=>{if(!e.target.dataset.orderStatus||!e.target.value)return;try{await request(`/orders/${e.target.dataset.orderStatus}/status`,{method:'PATCH',body:JSON.stringify({status:e.target.value,note:''})});notify('Order status updated');await loadAll()}catch(err){notify(err.message);await loadAll()}};
$('#order-details-dialog').onclick=async e=>{try{if(e.target.dataset.action==='change-order-status'){state.currentOrder=await request(`/orders/${state.currentOrder.summary.id}/status`,{method:'PATCH',body:JSON.stringify({status:$('#order-detail-status').value,note:$('#order-status-note').value})});e.currentTarget.close();notify('Order status updated');await loadAll();await showOrder(state.currentOrder.summary.id)}if(e.target.dataset.action==='open-order-designs')await showOrderDesigns(state.currentOrder)}catch(err){notify(err.message)}};
$('#artwork-form').onsubmit=async e=>{e.preventDefault();const body=new FormData(e.target);if(!body.get('customer_id'))body.delete('customer_id');if(!body.get('order_id'))body.delete('order_id');try{await request('/artwork',{method:'POST',body});e.target.closest('dialog').close();e.target.reset();notify('Design uploaded securely');await loadAll()}catch(err){notify(err.message)}};
$('#customer-list').onclick=async e=>{const action=e.target.dataset.customerAction;if(!action)return;const id=Number(e.target.dataset.id);try{if(action==='view')await showCustomer(id);if(action==='folder')await openCustomerFolder(id);if(action==='edit')fillCustomerForm(await getCustomer(id));if(action==='deactivate'&&confirm('Deactivate this customer?')){await request(`/customers/${id}/deactivate`,{method:'POST'});notify('Customer deactivated');await loadAll()}if(action==='delete'&&confirm('Permanently delete this customer? Linked customers cannot be deleted.')){await request(`/customers/${id}/permanent`,{method:'DELETE'});notify('Customer deleted');await loadAll()}}catch(err){notify(err.message)}};
$('#customer-details-dialog').onclick=async e=>{try{if(e.target.dataset.action==='edit-current-customer'){e.currentTarget.close();fillCustomerForm(state.currentCustomer)}if(e.target.dataset.action==='customer-folder'){e.currentTarget.close();await openCustomerFolder(state.currentCustomer.summary.id)}}catch(err){notify(err.message)}};
$('#customer-folder-tree').onclick=async e=>{if(!e.target.dataset.folder)return;state.selectedDate=e.target.dataset.date;state.selectedFolder=e.target.dataset.folder;$('#folder-location').textContent=`${state.currentCustomer.summary.display_identifier} / ${state.selectedDate} / ${state.selectedFolder}`;renderFolderDates();await loadCustomerFiles()};
$('#customer-file-list').onclick=e=>{const checkbox=e.target.closest('[data-select-file]');if(checkbox){const id=Number(checkbox.dataset.selectFile);checkbox.checked?selectedCustomerFileIds.add(id):selectedCustomerFileIds.delete(id);updateCustomerFileActions();return}const row=e.target.closest('[data-preview-file]');if(row)showCustomerFilePreview(state.files.find(f=>f.id===Number(row.dataset.previewFile)))};
$('#customer-file-list').ondblclick=e=>{const row=e.target.closest('[data-preview-file]');if(row)window.open(`${api}/customer-files/${row.dataset.previewFile}`,'_blank')};
$('#customer-folder-dialog').onclick=async e=>{const action=e.target.dataset.action;try{if(action==='folder-small')e.currentTarget.classList.remove('maximized');if(action==='folder-maximize')e.currentTarget.classList.add('maximized');if(action==='folder-back')e.currentTarget.close();if(action==='create-date-folder'){state.folder=await request(`/customers/${state.currentCustomer.summary.id}/folders`,{method:'POST',body:JSON.stringify({folder_date:null})});state.selectedDate=state.folder.dates.at(-1)||state.selectedDate;state.selectedFolder='Design';renderFolderDates();await loadCustomerFiles();notify('Today’s customer folders created')}if(action==='search-customer-files'){const q=prompt('Enter customer/design number, filename, or date:');if(q?.trim()){state.files=await request('/customer-files/search?query='+encodeURIComponent(q.trim()));selectedCustomerFileIds.clear();$('#folder-location').textContent=`All customers — Search: ${q.trim()}`;renderCustomerFiles();if(!state.files.length)showCustomerFilePreview(null)}}if(action==='open-selected-file'){const files=selectedCustomerFiles();if(files.length===1)window.open(`${api}/customer-files/${files[0].id}`,'_blank');else notify('Select one file to open.')}if(action==='download-selected-files'){const files=selectedCustomerFiles();if(!files.length)return notify('Select one or more files first.');for(const file of files){const link=document.createElement('a');link.href=`${api}/customer-files/${file.id}`;link.download=file.original_name;link.click()}}if(action==='copy-selected-files')await openCopyFilesDialog();if(action==='delete-selected-files'){const files=selectedCustomerFiles();if(files.length&&confirm(`Permanently delete ${files.length===1?'"'+files[0].original_name+'"':files.length+' selected files'}?`)){for(const file of files)await request(`/customer-files/${file.id}`,{method:'DELETE'});await loadCustomerFiles();notify('Selected files deleted')}}if(action==='edit-selected-file'){const files=selectedCustomerFiles();if(files.length!==1)return notify('Select one image file to edit.');const file=files[0];if(!file.content_type.startsWith('image/'))return notify('Select an image file to open the editor.');$('#customer-editor-title').textContent=`Image Editor — ${file.original_name}`;$('#customer-editor-preview').innerHTML=`<img src="${api}/customer-files/${file.id}" alt="">`;$('#customer-image-editor-dialog').showModal()}}catch(err){notify(err.message)}};
$('#customer-file-upload').onchange=async e=>{if(!state.selectedDate)return notify('Create today’s folders first.');if(state.selectedFolder!=='Design')return notify('Manual imports are allowed only in the Design folder.');try{for(const file of e.target.files){const body=new FormData();body.append('file',file);body.append('date_name',state.selectedDate);body.append('folder_name',state.selectedFolder);await request(`/customers/${state.currentCustomer.summary.id}/files`,{method:'POST',body})}e.target.value='';await loadCustomerFiles();notify('Files uploaded')}catch(err){notify(err.message)}};
$('#customer-image-search').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const body=new FormData();body.append('file',file);state.files=await request('/customer-files/search-image',{method:'POST',body});renderCustomerFiles();e.target.value='';notify(`${state.files.length} similar files found`)}catch(err){notify(err.message)}};
$('#replace-customer-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const body=new FormData();body.append('file',file);await request(`/customers/${state.currentCustomer.summary.id}/files/${e.target.dataset.fileId}/replace`,{method:'POST',body});e.target.value='';await loadCustomerFiles();notify('File replaced')}catch(err){notify(err.message)}};
$('#copy-files-form [name=customer_id]').onchange=()=>loadCopyDates().catch(err=>notify(err.message));
$('#copy-files-form').onsubmit=async e=>{e.preventDefault();const form=e.target;try{for(const fileId of form.dataset.fileIds.split(','))await request(`/customers/files/${fileId}/copy`,{method:'POST',body:JSON.stringify({customer_id:Number(form.elements.customer_id.value),date_name:form.elements.date_name.value,folder_name:form.elements.folder_name.value})});form.closest('dialog').close();await loadCustomerFiles();notify('Selected files copied')}catch(err){notify(err.message)}};
window.addEventListener('online',()=>{$('#connection').textContent='Online';$('#connection').classList.remove('offline')});window.addEventListener('offline',()=>{$('#connection').textContent='Offline';$('#connection').classList.add('offline')});
request('/auth/me').then(showApp).catch(showLogin);
