"use client";

import { useParams, useRouter } from "next/navigation";
import { Eye, Share2, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import MobileHeader from "./components/MobileHeader";
import BottomNav from "./components/BottomNav";
import DesignPreviewEditor from "./DesignPreviewEditor";

type Design = { id: number; name: string; preview_url: string; file_url: string; notes?: string | null; created_at?: string };

export default function DesignDetailsPage() {
  const params = useParams<{ id: string }>(); const router = useRouter(); const [design, setDesign] = useState<Design | null>(null); const [preview, setPreview] = useState(false); const [message, setMessage] = useState(""); const [dimensions, setDimensions] = useState({ width: "—", height: "—" });
  useEffect(() => { fetch(`/api/designs/${params.id}`, { cache: "no-store", credentials: "include" }).then((r) => r.ok ? r.json() : null).then(setDesign).catch(() => setMessage("Unable to load design")); }, [params.id]);
  async function remove() { if (!design || !window.confirm("Delete this design?")) return; const response = await fetch(`/api/designs/${design.id}`, { method: "DELETE", credentials: "include" }); if (response.ok) router.push("/designs"); else setMessage("Unable to delete design"); }
  useEffect(() => { if (!design?.preview_url) return; try { const metadata = JSON.parse(design.notes || "{}"); if (metadata.width && metadata.height) { setDimensions({ width: `${Number(metadata.width).toFixed(2)} in`, height: `${Number(metadata.height).toFixed(2)} in` }); return; } } catch { /* Older designs may have plain-text notes. */ } const image = new window.Image(); image.onload = () => setDimensions({ width: `${(image.naturalWidth / 300).toFixed(2)} in`, height: `${(image.naturalHeight / 300).toFixed(2)} in` }); image.src = design.preview_url; }, [design?.preview_url, design?.notes]);
  async function share() { if (!design) return; try { const image = new window.Image(); image.crossOrigin = "anonymous"; image.src = design.preview_url; await new Promise((resolve, reject) => { image.onload = resolve; image.onerror = reject; }); const canvas = document.createElement("canvas"); canvas.width = image.naturalWidth || 1200; canvas.height = image.naturalHeight || 1200; const context = canvas.getContext("2d"); if (!context) throw new Error("Preview canvas unavailable"); const cell = Math.max(12, Math.round(canvas.width / 30)); for (let y = 0; y < canvas.height; y += cell) for (let x = 0; x < canvas.width; x += cell) { context.fillStyle = (x / cell + y / cell) % 2 === 0 ? "#f0eef5" : "#ffffff"; context.fillRect(x, y, cell, cell); } context.drawImage(image, 0, 0, canvas.width, canvas.height); const blob = await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, "image/png")); if (!blob) throw new Error("Preview image could not be prepared"); const file = new File([blob], `${design.name.replace(/\.[^.]+$/, "")}-preview.png`, { type: "image/png" }); if (navigator.share && (!navigator.canShare || navigator.canShare({ files: [file] }))) await navigator.share({ title: `${design.name} preview`, files: [file] }); else { const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = file.name; link.click(); URL.revokeObjectURL(link.href); } setMessage("Preview shared with checkerboard background"); } catch { setMessage("Preview sharing was cancelled or unavailable"); } }
  async function savePreview(imageUrl: string, notes: string) { if (!design) return; let previewUrl = imageUrl; try { previewUrl = new URL(imageUrl, window.location.origin).pathname; } catch { /* Keep the original value so the API can report a useful error. */ } const response = await fetch(`/api/designs/${design.id}`, { method: "PATCH", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ notes, preview_url: previewUrl }) }); const result = await response.json().catch(() => ({})); const detail = Array.isArray(result.detail) ? result.detail.map((item: { msg?: string }) => item.msg || "Validation error").join("; ") : String(result.detail || "Unable to save preview settings"); if (!response.ok) { setMessage(detail); return; } setDesign(result.design); setPreview(false); setMessage("Preview settings saved to the design"); }
  if (!design) return <main className="or-profile-page"><div className="or-profile-scroll"><MobileHeader title="Design Details" onBack={() => history.back()} /><p>{message || "Loading design…"}</p></div></main>;
  return <main className="or-profile-page"><div className="or-profile-scroll"><MobileHeader title="Design Details" onBack={() => history.back()} /><section className="or-design-detail-preview measured"><div className="design-measure-width"><span>↔</span>{dimensions.width}<span>↔</span></div><div className="design-measure-height"><span>↕</span>{dimensions.height}</div><img src={design.preview_url} alt={design.name} /></section><section className="or-design-detail-name"><strong>{design.name}</strong><small>{design.created_at ? new Date(design.created_at).toLocaleDateString() : "Uploaded design"}</small></section><div className="or-design-actions"><button type="button" onClick={() => setPreview(true)}><Eye size={20} />Preview</button><button type="button" onClick={share}><Share2 size={20} />Share</button><button type="button" className="danger" onClick={remove}><Trash2 size={20} />Delete</button></div><section className="or-detail-table"><h3>Details</h3><div><span>Width</span><b>{dimensions.width}</b></div><div><span>Height</span><b>{dimensions.height}</b></div><div><span>File</span><b>{design.name}</b></div><div><span>Preview controls</span><b>Size · Background · Upscale</b></div></section>{message ? <p role="status">{message}</p> : null}</div><BottomNav />{preview ? <DesignPreviewEditor designId={design.id} name={design.name} imageUrl={design.preview_url} initialNotes={design.notes} onClose={() => setPreview(false)} onSaved={savePreview} /> : null}</main>;
}
