"""initial schema

Revision ID: 867624c49566
Revises: 
Create Date: 2026-09-06 23:30:48.419552
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '867624c49566'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=160), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('business_name', sa.String(length=160), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('gst_number', sa.String(length=24), nullable=True),
    sa.Column('level', sa.String(length=40), nullable=False),
    sa.Column('account_manager', sa.String(length=120), nullable=True),
    sa.Column('security_note', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_mobile'), 'customers', ['mobile'], unique=True)
    op.create_index(op.f('ix_customers_public_id'), 'customers', ['public_id'], unique=True)
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('width_inches', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('speed_mph', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('cost_per_meter', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('designs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('external_erp_id', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('preview_key', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_designs_customer_id'), 'designs', ['customer_id'], unique=False)
    op.create_index(op.f('ix_designs_external_erp_id'), 'designs', ['external_erp_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('external_erp_id', sa.String(length=80), nullable=True),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'ARTWORK_CHECKING', 'AWAITING_APPROVAL', 'AWAITING_PAYMENT', 'PAYMENT_CONFIRMED', 'IN_QUEUE', 'PRINTING', 'QC', 'PACKED', 'DISPATCHED', 'DELIVERED', 'COMPLETED', name='customerorderstatus'), nullable=False),
    sa.Column('total_meters', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rate_per_meter', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_snapshot', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_external_erp_id'), 'orders', ['external_erp_id'], unique=False)
    op.create_index(op.f('ix_orders_public_id'), 'orders', ['public_id'], unique=True)
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('gangsheet_version', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_order_id'), 'approvals', ['order_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_order_id'), 'invoices', ['order_id'], unique=False)
    op.create_index(op.f('ix_invoices_public_id'), 'invoices', ['public_id'], unique=True)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('sender_type', sa.String(length=20), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_customer_id'), 'messages', ['customer_id'], unique=False)
    op.create_index(op.f('ix_messages_order_id'), 'messages', ['order_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_public_id'), 'payments', ['public_id'], unique=True)
    op.create_table('production_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('operator_name', sa.String(length=120), nullable=True),
    sa.Column('expected_meters', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actual_meters', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('waste_meters', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_jobs_order_id'), 'production_jobs', ['order_id'], unique=False)
    op.create_index(op.f('ix_production_jobs_public_id'), 'production_jobs', ['public_id'], unique=True)
    op.create_table('reprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reprints_order_id'), 'reprints', ['order_id'], unique=False)
    op.create_index(op.f('ix_reprints_public_id'), 'reprints', ['public_id'], unique=True)
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('courier', sa.String(length=80), nullable=False),
    sa.Column('awb', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_order_id'), 'shipments', ['order_id'], unique=False)
    op.create_index(op.f('ix_shipments_public_id'), 'shipments', ['public_id'], unique=True)
    op.create_table('support_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('issue', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_tickets_customer_id'), 'support_tickets', ['customer_id'], unique=False)
    op.create_index(op.f('ix_support_tickets_public_id'), 'support_tickets', ['public_id'], unique=True)
    op.create_table('quality_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('defect_reason', sa.Text(), nullable=True),
    sa.Column('checked_by', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['production_job_id'], ['production_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_checks_production_job_id'), 'quality_checks', ['production_job_id'], unique=False)
    op.create_table('waste_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_job_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('meters', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['production_job_id'], ['production_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waste_events_production_job_id'), 'waste_events', ['production_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waste_events_production_job_id'), table_name='waste_events')
    op.drop_table('waste_events')
    op.drop_index(op.f('ix_quality_checks_production_job_id'), table_name='quality_checks')
    op.drop_table('quality_checks')
    op.drop_index(op.f('ix_support_tickets_public_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_customer_id'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index(op.f('ix_shipments_public_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_order_id'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_reprints_public_id'), table_name='reprints')
    op.drop_index(op.f('ix_reprints_order_id'), table_name='reprints')
    op.drop_table('reprints')
    op.drop_index(op.f('ix_production_jobs_public_id'), table_name='production_jobs')
    op.drop_index(op.f('ix_production_jobs_order_id'), table_name='production_jobs')
    op.drop_table('production_jobs')
    op.drop_index(op.f('ix_payments_public_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_messages_order_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_customer_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_invoices_public_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_order_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_approvals_order_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_orders_public_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_external_erp_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_designs_external_erp_id'), table_name='designs')
    op.drop_index(op.f('ix_designs_customer_id'), table_name='designs')
    op.drop_table('designs')
    op.drop_table('suppliers')
    op.drop_table('machines')
    op.drop_index(op.f('ix_customers_public_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_mobile'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
